version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    working_dir: /home
    volumes:
      - .:/home
      - node_modules:/home/node_modules

volumes:
  node_modules:
    driver: 'local'
