export const LANTICA_GEAR_GRAPHIC_SIZE = 160;
export const LANTICA_GEAR_TEETH_COUNT = 16;
export const LANTICA_GEAR_TEETH_HEIGHT = 7;
export const LANTICA_INIT_RADIAN = Math.PI * 2 / (LANTICA_GEAR_TEETH_COUNT * 2 * 2);

export const LANTICA_GEAR_COLOR_PRIMARY = '#B68765'
export const LANTICA_GEAR_COLOR_DARK = '#7C553C'
export const LANTICA_GEAR_COLOR_LIGHT = '#FFD4A1'

export const KIRIKO_RADIUS = 55;
export const KOGANE_RADIUS = 60;
export const MAMIMI_RADIUS = 55;
export const SAKUYA_RADIUS = 75;

export const ROMAN_NUMBER_GRAPHIC_SIZE = 48;
export const YUIKA_RADIUS = 300;
export const YUIKA_FACE_RADIUS = 260;
export const YUIKA_FACE_INNER_CIRCLE_RADIUS = 35;

export const KIRIKO_COLOR = '#D9F2FF';
export const KOGANE_COLOR = '#F84CAD';
export const MAMIMI_COLOR = '#A846FB';
export const SAKUYA_COLOR = '#006047';
export const YUIKA_COLOR = '#3B91C4';

export const LANTICA_COLORS = [KIRIKO_COLOR, KOGANE_COLOR, MAMIMI_COLOR, SAKUYA_COLOR];
