export const LANTICA_GEAR_GRAPHIC_SIZE = 160;
export const LANTICA_GEAR_TEETH_COUNT = 16;
export const LANTICA_GEAR_TEETH_HEIGHT = 7;
export const LANTICA_INIT_RADIAN = Math.PI * 2 / (LANTICA_GEAR_TEETH_COUNT * 2 * 2);

export const LANTICA_GEAR_COLOR_PRIMARY = '#B68765'
export const LANTICA_GEAR_COLOR_DARK = '#7C553C'
export const LANTICA_GEAR_COLOR_LIGHT = '#FFD4A1'

export const KIRIKO_RADIUS = 55;
export const YUIKA_RADIUS = 300;
