export const LANTICA_GEAR_GRAPHIC_SIZE = 160;
export const LANTICA_GEAR_TEETH_COUNT = 16;
export const LANTICA_GEAR_TEETH_HEIGHT = 10;
export const LANTICA_GEAR_COLOR_PRIMARY = '#B68765'
export const LANTICA_GEAR_COLOR_DARK = '#7C553C'
export const LANTICA_GEAR_COLOR_LIGHT = '#FFD4A1'
